# Generated by Django 5.2 on 2025-04-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'verbose_name': 'Business Info', 'verbose_name_plural': 'Business Info'},
        ),
    ]
