# Generated by Django 5.2 on 2025-04-27 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Daily Menu',
                'verbose_name_plural': 'Daily Menus',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='menu_item_price_gte_0)', violation_error_message='Price must be greater than or equal to 0'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='menu_items',
            field=models.ManyToManyField(related_name='daily_menus', to='menu.menuitem'),
        ),
    ]
