# Generated by Django 5.2 on 2025-04-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dailymenu_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
    ]
