# Generated by Django 5.2 on 2025-05-01 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank app', 'Bank App')], default='cash', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='orders.order')),
            ],
            options={
                'ordering': ('-payment_time',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0.0)), name='sale_amount_gte_0', violation_error_message='Amount must be greater than or equal to 0')],
            },
        ),
    ]
